from rest_framework import serializers
from .models import BlogPost
# SEMPRE QUE TRABALHMOS COM O DJANGO-RESTFRAMEWORK
# DEVEMOS CRIAR UM ARQUIVO "SERIALIZERS.PY"
# QUE TEM COMO PRINCIPAL FUNCIONALIDADE SERIALIZAR OS DADOS
# OU SEJA, ELE SERVE COMO UM INTÉRPRETE DOS DADOS EM JSON 
# PARA O NOSSO BACKEND EM PYTHON PODER CONSUMI-LOS


# SUA ESTRURA É BEM SIMPLES:
# CRIAMOS UMA CLASSE E PASSAMOS SEUS PARÂMETROS "SERIALIZER.MODELSERIALIZER"
# COMO ATRIBUTO, PASSAMOS O MODELO QUE SERÁ UTILIZADO NESSE APP, E OS CAMPOS A SEREM CONSUMIDOS

class BlogPostSerializer(serializers.ModelSerializer):
    class Meta:
        model = BlogPost
        fields = '__all__'
        lookup_field = 'slug'